disabled_rules:
  # We have documented what we intend documented.
  - valid_docs

  - conditional_binding_cascade
  - empty_parentheses_with_trailing_closure

  # Prevent griping about: let _ = …
  # Having the |let| makes giving it a name in debugging easier.
  - redundant_discardable_let

  # Prevent griping about: let _ = …
  # Having the |let| makes giving it a name in debugging easier,
  # plus, it phrases it as a positive test rather than a negative one,
  # which is especially valuable in an effectively
  # already-negated-once guard clause.
  - unused_optional_binding

included:

excluded:
  - Carthage
  - Pods

# Overrides

line_length: 175

type_name:
  min_length: 4
  max_length: 50
function_parameter_count: 10
function_body_length: 50
